# ==============================================================
# SMART LIBRARY CORE - CONFIGURAÇÕES DO SPRING BOOT
# ==============================================================

# --- Perfil Ativo ---
spring.profiles.active=dev

# --- Configurações do Servidor ---
server.port=8080
server.servlet.context-path=/api

# --- Configuração de Log Simples (Console) ---
logging.level.mz.com.dimasoft.smartlibrary=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

# --- Configuração do OAuth2 Resource Server ---
# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/smart-library
