# --- Configurações de Conexão com a Base de Dados (PostgreSQL - Neon.tech) ---
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://ep-misty-king-b5h5upnx-pooler.c-7.us-east-2.aws.neon.tech/smart-library-db?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_7GMRz3BiKwxh}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configurações do JPA e Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
